### ISSUE TITLE
Error after the setup

### ISSUE THREAD

**Issue by szbstvn** [paylike/plugin-prestashop-1.7#17]
After the install i try set up with keys but i got this:

"[PrestaShop] Fatal error in module file: /home/playameh/public_html/app/bootstrap.php.cache:3225
Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "Paylike" from namespace "Paylike". Did you forget a "use" statement for another namespace? in /home/playameh/public_html/modules/paylikepayment/paylikepayment.php:625 Stack trace: #0 /home/playameh/public_html/modules/paylikepayment/paylikepayment.php(234): PaylikePayment->validateAppKeyField('d3438fc6-85d6-4...', 'live') #1 /home/playameh/public_html/controllers/admin/AdminModulesController.php(906): PaylikePayment->getContent() #2 /home/playameh/public_html/controllers/admin/AdminModulesController.php(1165): AdminModulesControllerCore->postProcessCallback() #3 /home/playameh/public_html/classes/controller/Controller.php(194): AdminModulesControllerCore->postProcess() #4 /home/playameh/public_html/classes/Dispatcher.php(379): ControllerCore->run() #5 /home/playameh/public_html/admin098qapa86/index.php(95): DispatcherCore->dispatch() #6 {main} Next LogicException: Request stack is empty in /home/playameh/public_html/a"

Prestashop is 1.7.2

What is the soultion? Earlier version? I cannot update the prestashop ...

**Comment by ionutcalara** [comment]
Hi @szbstvn I think the error is due to your PHP version. we've found a potential fix that we are testing. You can see the change here: https://github.com/paylike/plugin-prestashop-1.7/pull/18/files. I will ping you here again once the update is available.

**Comment by ionutcalara** [comment]
Hi @szbstvn you can download this version here and replace your module: https://github.com/paylike/plugin-prestashop-1.7/blob/master/paylikepayment.zip . This should work. I will close the issue for now, but please reopen if the update doesn't work for you.
