### ISSUE TITLE
It's not compatible with the supercheckout module

### ISSUE THREAD

**Issue by garciasanchezdani** [paylike/plugin-prestashop-1.7#26]
It's not compatible with the supercheckout module.

SuperCheckout v5.0.9 - by Knowband

I have seen that, in /modules/paylikepayment/views/templates/hook/payment.tpl:166, PayLikePayment.init() is not executed.

**Comment by cosminbosutar** [comment]
Hello @garciasanchezdani 

Thank you for mentioning this.

Currently, the plugin is compatible with the [One Page Checkout PS Module](https://addons.prestashop.com/en/express-checkout-process/8503-one-page-checkout-ps-easy-fast-intuitive.html#specifications) one page checkout plugin.

Thank you!

**Comment by ionutcalara** [comment]
Hi @garciasanchezdani, as my colleague mentioned, we currently support https://addons.prestashop.com/en/express-checkout-process/8503-one-page-checkout-ps-easy-fast-intuitive.html#specifications which was one of the most popular one page checkout modules when we did our research. If the team behind SuperCheckout want's to make their plugin compatible with our payment gateway, we're glad to assist. 

I am closing this issue, but feel free to reopen.
