### ISSUE TITLE
The getPaylikeAmount(...) call is passing a incorrect value for $currency_iso_code argument.

### ISSUE THREAD

**Issue by juhchamp** [paylike/plugin-prestashop-1.7#31]
The method ` getPaylikeAmount( $total, $currency_iso_code )`  waits for a `currency iso code` at second argument, but at the line 750, you have passed the `$currency_multiplier` variable value instead of a valid `currency iso code` value like the `$currency_code` variable value at line 748.
https://github.com/paylike/plugin-prestashop-1.7/blob/e5551a25f69477c6dd1a25b110c82325be086d5b/paylikepayment/paylikepayment.php#L748-L750

**Comment by cosminbosutar** [comment]
Hello @juhchamp,

Thank you for mentioning this.

We'll update the code.

Thank you!
Cosmin

**Comment by ionutcalara** [comment]
This has been patched in the latest release. I am closing this, but feel free to reopen. 
https://github.com/paylike/plugin-prestashop-1.7/releases/download/v1.1.2/paylikepayment.zip
